## dataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.2.200:8420/eureka/
    register-with-eureka: false


hikari:
  jdbcurl: empty
  username: root
  password:
  driverclassname: com.mysql.jdbc.Driver
  maximumPoolSize: 20
  idleTimeout: 60000
  connectTimeout: 5000
  maxLifetime: 1800000